name: Run Deal Scraper

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Enables manual run button

jobs:
  run-deal-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Supabase Edge Function
        run: |
          curl -X POST https://nouijnpwoomjjobpkzmp.supabase.co/functions/v1/deal-scraper \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTY5...REDACTED..." \
            -H "Content-Type: application/json" \
            -d '{}'
